### ISSUE TITLE
Some extensions missing from category Diffusion & Tractography

### ISSUE THREAD

**Issue by ihnorton** [Slicer/slicer-wiki-scripts#5]
The scripts here seem to update the following page:
http://wiki.slicer.org/slicerWiki/index.php/Documentation/4.5#Modules_by_category_Diffusion

some extensions with category Diffusion are missing from the list, e.g. 
https://github.com/Slicer/ExtensionsIndex/blob/master/DTIPrep.s4ext
https://github.com/Slicer/ExtensionsIndex/blob/master/FiberViewerLight.s4ext

(let me know if the issue should be opened elsewhere instead)

**Comment by jcfr** [comment]
The extensions are listed on the "known to be broken" page.

See http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/ModuleExtensionListing/Broken#Broken_extensions_by_category_Diffusion

This probably means that the extension can not be build, packaged or loaded on neither of the platform (Linux, MacOSX, Windows)

Looking at yesterday's dashboard, this confirms the hypothesis: http://slicer.cdash.org/index.php?project=Slicer4&date=2016-01-12&subproject=DTIPrep

**Comment by jcfr** [comment]
The newly generated Nightly page now list the modules.
See https://www.slicer.org/wiki/Documentation/Nightly/ModuleExtensionListing/Modules_by_extension#SlicerDMRI
